#!/usr/bin/env bash
set -euo pipefail

readonly PACKAGE_JSON_BACKUP_FILE=package.json.backup

cleanup_package_json() {
    local FIELDS_TO_KEEP="\"author\",\"bugs\",\"dependencies\",\"description\",\"engines\",\"files\",\"keywords\",\"license\",\"main\",\"name\",\"repository\",\"scripts\",\"typings\",\"version\""
    local SCRIPTS_TO_KEEP="\"postpack|postpublish|postrelease\""
    local REGEX="(${SCRIPTS_TO_KEEP})"

    jq "{${FIELDS_TO_KEEP}}" ${PACKAGE_JSON_BACKUP_FILE} | \
    jq 'with_entries(select(.value |. != null))' | \
    jq ".scripts|=with_entries(select(.key|test(${REGEX})))" > package.json
}

# TODO: run size-limit? snyk?

echo "Backup original package.json"
cp package.json ${PACKAGE_JSON_BACKUP_FILE}

# https://stackoverflow.com/questions/48802204/npm-publish-removing-scripts-from-package-json
# https://github.com/roydukkey/clean-package
echo "Cleanup package.json from unnecessary fields and scripts"
cleanup_package_json

echo "Here is the package.json stripped of unnecessary fields"
jq '.' package.json
