#!/usr/bin/env bash
set -euo pipefail

# For testing this script
# PREVIOUS_VERSION=0.0.0
# VERSION=0.0.1

readonly PACKAGE_JSON_BACKUP_FILE=package.json.backup

# We need to bump "version" in package.json before generating a CHANGELOG.
# However, xyz bumps "version" too. To avoid a double bump, we save and restore
# package.json.
update_changelog() {
    # VERSION and PREVIOUS_VERSION are environment variables set by xyz
    echo "Update CHANGELOG.md: ${PREVIOUS_VERSION} ==> ${VERSION}"

    [ -f ${PACKAGE_JSON_BACKUP_FILE} ] && rm ${PACKAGE_JSON_BACKUP_FILE}
    cp package.json ${PACKAGE_JSON_BACKUP_FILE}

    # jq cannot edit files in place
    # https://github.com/stedolan/jq/issues/105
    # https://stackoverflow.com/questions/36565295/jq-to-replace-text-directly-on-file-like-sed-i
    jq ".version|=\"${VERSION}\"" package.json > package.json.tmp && \
    mv package.json.tmp package.json

    auto-changelog --package --sort-commits date-desc --commit-limit false
    git add CHANGELOG.md

    rm package.json
    mv ${PACKAGE_JSON_BACKUP_FILE} package.json
}

update_changelog
