#!/bin/sh

# Husky seems to run all hook scripts using sh, regardless of the shebang present
# in the git hook.
# https://github.com/typicode/husky/issues/971
. "$(dirname "$0")/_/husky.sh"

# https://vaneyckt.io/posts/safer_bash_scripts_with_set_euxo_pipefail/
set -eu

echo "PRE PUSH HOOK [destination remote: $1] [location remote: $2]"

# TODO: ideally we do NOT want to run this git hook when the git plugin of
# semantic-release pushes tags, but I still haven't found a solution for this.
# https://stackoverflow.com/questions/20551613/git-pre-push-hook-dont-run-if-is-tags
npm run prepush
