name: CI
on: [push]
jobs:
  build:
    name: Build, lint, and test on Node ${{ matrix.node }} and ${{ matrix.os }}

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: ['10.x', '12.x', '14.x']
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Use Node ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - name: Install deps and build (with cache)
        uses: bahmutov/npm-install@v1

      - name: Lint
        run: yarn lint

      - name: Test
        run: CLOUDINARY_CLOUD_NAME=${{ secrets.CLOUDINARY_CLOUD_NAME }} CLOUDINARY_API_KEY=${{ secrets.CLOUDINARY_API_KEY }} CLOUDINARY_API_SECRET=${{ secrets.CLOUDINARY_API_SECRET }} CLOUDINARY_IMAGE_PUBLIC_ID=${{ secrets.CLOUDINARY_IMAGE_PUBLIC_ID }} yarn test --ci --coverage --maxWorkers=2

      - name: Build
        run: yarn build
