name: "Notify when CI workflow fails"
on:
  workflow_run:
    workflows: ["CI"]
    types: [completed]
jobs:
  on-failure:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    env:
      REPO_NAME: ${{ github.event.repository.full_name }}
      REPO_URL: ${{ github.event.repository.html_url }}
      WORKFLOW_RUN_URL: ${{ github.event.workflow_run.html_url }}
      WORKFLOW_RUN_CREATED_AT: ${{ github.event.workflow_run.created_at }}
    steps:
      - name: Notify Telegram of failed CI run
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          # https://emojipedia.org/
          message: |
            ⚠️ FAILED CI WORKFLOW! 😭
            Repo: ${{ env.REPO_URL }}.
            Workflow run: ${{ env.WORKFLOW_RUN_URL }}
            Workflow run created at: ${{ env.WORKFLOW_RUN_CREATED_AT }}
