name: 'Notify of workflow failure'

on:
  workflow_run:
    workflows: ['CI']
    types: [completed]

jobs:
  on-failure:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - name: 💬 Notify Telegram chat about failed GitHub workflow run
        # https://github.com/appleboy/telegram-action
        uses: appleboy/telegram-action@v0.1.1
        # This is a container action, so it must run on Linux (it would fail if
        # `runs-on` is either `windows-latest` or `macOS-latest`)
        # https://docs.github.com/en/actions/creating-actions/creating-a-docker-container-action#introduction
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          format: html
          disable_web_page_preview: true
          # https://core.telegram.org/bots/api#formatting-options
          message: |
            <b>⚠️ GitHub workflow run failed 💔</b>

            Repository: <a href="${{ github.event.repository.html_url }}">${{ github.event.repository.full_name }}</a>

            <a href="${{ github.event.workflow_run.html_url }}">GitHub Workflow run</a>
