name: "Notify when CI workflow fails"
on:
  workflow_run:
    workflows: ["CI"]
    types: [completed]
jobs:
  on-success:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Send success message to Telegram
        uses: appleboy/telegram-action@master
        env:
          REPO_NAME: ${{ github.event.repository.full_name }}
          REPO_URL: ${{ toJSON(github.event.repository.html_url) }}
          WORKFLOW_URL: ${{ github.event.workflow_run.html_url }}
          CREATED_AT: ${{ github.event.workflow_run.created_at }}
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            ${{ github.event.repository.full_name }} and ${{ env.REPO_NAME }} or $REPO_NAME "$REPO_NAME".
            echo This event is a pull request that had an assignee removed.
            ${{ github.event.repository.html_url }} and ${{ toJSON(github.event.repository.html_url) }}.
            Workflow run URL ${{ github.event.workflow_run.html_url }}
            Workflow run created at: ${{ github.event.workflow_run.created_at }}
  on-failure:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - name: Send custom message to Telegram with args
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            The CI workflow failed.
