name: 'Notify when CI workflow fails'

on:
  workflow_run:
    workflows: ['CI']
    types: [completed]

jobs:
  on-failure:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    env:
      REPO_NAME: ${{ github.event.repository.full_name }}
      REPO_URL: ${{ github.event.repository.html_url }}
      WORKFLOW_RUN_URL: ${{ github.event.workflow_run.html_url }}
    steps:
      - name: Notify Telegram chat about failed CI run
        # https://github.com/appleboy/telegram-action
        uses: appleboy/telegram-action@v0.1.1
        # This is a container action, so it must run on Linux (it would fail if
        # `runs-on` is either `windows-latest` or `macOS-latest`)
        # https://docs.github.com/en/actions/creating-actions/creating-a-docker-container-action#introduction
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          format: html
          disable_web_page_preview: true
          # https://core.telegram.org/bots/api#formatting-options
          message: |
            <b>⚠️ GitHub workflow 'CI' failed in ${{ github.repository }} 💔</b>
            
            Repository: <a href="https://github.com/${{ github.repository }}/">${{ github.repository }}</a>

            Workflow run: <a href="${{ github.event.workflow_run.html_url }}">${{ github.event.workflow_run.html_url }}</a>
            
            Workflow run created at: ${{ github.event.workflow_run.created_at }}
